### ISSUE TITLE
Only plugins.var.weecord.token shows up as an option

### ISSUE THREAD

**Issue by FredrIQ** [khyperia/weechat-discord#34] opened 2017-07-27 01:10 UTC
Possibly other options aren't populated correctly?

**Comment by khyperia** [comment] 2017-07-27 01:38
Please describe more what you mean by "shows up as an option", and what you mean by "populating correctly" - a clearly thought out and articulated issue report describing expected behavior, actual behavior, suggested fixes, etc., is essential in getting the problem resolved. With the title/description as-is, I assume this is a duplicate of #13 and am closing until otherwise notified. Please look at existing issues before reporting additional issues.

**Closed as completed by khyperia** 2017-07-27 01:38 UTC

**Comment by FredrIQ** [comment] 2017-07-27 01:53
#13 is rather technical regarding weechat internals, so in case this is actually a duplicate, it definitely wasn't clear. With that said, 1bb57f0d640431598da0 claims to have added mute.(channel id) as options, populated automatically as you connect or discord sends an update. However, when i wanted to look at these options, using /set *mute*, the only options that showed up was iset.use_mute and fset.use_mute (weechat 2.0-dev iset equavilent-ish thing), so there didn't seem to be any such options. I also did /set plugins.var.weecord.*, the only option I got was .token. Hence this issue.

**Comment by khyperia** [comment] 2017-07-27 14:47
Correct. The options are not registered, but dynamically checked (as weechat's config system is mostly just a big untyped bag of key->value dict of string->string). The options exist (see `/help discord`), just set them :)

The reason "only token shows up" is because that's the only one you have set. It "doesn't exist" either, if it were unset.
